### ISSUE TITLE
Error : '' is not a valid floating point value. when click on "Generating"

### ISSUE THREAD

**Issue by kristof33** [sb53systems/G-Code-Flow-Temperature-Controller#10]
Hello,

When I click on "Generating", I have this Error : '' is not a valid floating point value. (in french : '' n'est pas une valeur en virgule flottante correcte.)

![image](https://github.com/user-attachments/assets/01d48a68-9677-4d74-b8df-0324f9a6667c)

![image](https://github.com/user-attachments/assets/e3dc3e1d-d823-449b-9f38-2a3b71fed91b)

It seems to be a problem with regional parameters : . or , ?

Thanks so much for your helps.

[3DBenchy_PLA_49m21s.gcode.txt](https://github.com/user-attachments/files/16840981/3DBenchy_PLA_49m21s.gcode.txt)

**Comment by sb53systems** [comment]
@kristof33 you have to change the name of the print start macro to : PRINT_START, you have to set the same name in klipper .cfg file too.

Best Regards.Salim.

**Comment by sb53systems** [comment]
Let me know if you have trouble.

**Comment by kristof33** [comment]
> @kristof33 you have to change the name of the print start macro to : PRINT_START, you have to set the same name in klipper .cfg file too.
> 
> Best Regards.Salim.

That works now.

Thanks for the clue.
